### ISSUE TITLE
README has wrong version number

### ISSUE THREAD

**Issue by anna-is-cute** [aadnk/PacketWrapper#1]
This is purely aesthetic, but the README says 1.5.1, when the commits indicate that this has been updated for 1.6.1. I don't really think it's worth a PR, since this is a really simple change. It's barely even an issue!

**Comment by aadnk** [comment]
Done and done. :)

**Comment by anna-is-cute** [comment]
Have to say that's the fastest I've ever seen an issue handled.

**Comment by aadnk** [comment]
Well, I happened to be at the computer when I got an email notification ...

And then updating the readme is a fairly quick operation. But yeah, let me know if you find any other problems - I'm sure there are a couple of mistakes lurking in some of the auto-generated classes. Or perhaps some are missing a few useful properties.

I don't have to consider backwards compatibility with this project, as its only intended as a repository of example code to be copied from. I can make breaking changes. :)
