### ISSUE TITLE
WrapperPlayClientClientCommand IndexOutOfBoundsException

### ISSUE THREAD

**Issue by kangarko** [aadnk/PacketWrapper#8]
Hello,
I would like to instant respawn a player after his death, but I am getting this error:
Error + code:
http://pastebin.com/6bhKnPhw

I tried also 
packet.setCommand(WrapperPlayClientClientCommand.Commands.RESPAWN_AFTER_DEATH);
 but didn´t with the same result.

Greetings,
kangarko

**Comment by aadnk** [comment]
Ah - I must have missed WrapperPlayClientClientCommand when I updated it for 1.7.2.

Try the latest version on GitHub and see if that works (remember to also update AbstractPacket):

``` java
public class ExampleMod extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onAutoRespawn(PlayerDeathEvent e) {
        final Player player = e.getEntity();

        getServer().getScheduler().scheduleSyncDelayedTask(this, new Runnable() {
            @Override
            public void run() {
                WrapperPlayClientClientCommand packet = new WrapperPlayClientClientCommand();
                packet.setCommand(ClientCommand.PERFORM_RESPAWN);
                packet.recievePacket(player);
            }
        }, 1);
    }
}
```
